pip install --upgrade jinja2
pip install --upgrade jsonschema
pip install --upgrade toolz
pip install --upgrade packaging
pip install --upgrade tqdm
pip install --upgrade entrypoints
pip install --upgrade pandas
pip install --upgrade pyodbc
pip install --upgrade selenium
pip install --upgrade flask
pip install --upgrade requests
pip install --upgrade openpyxl
pip install --upgrade SQLAlchemy 